### ISSUE TITLE
Warning: GPU accelerator label contains a poorly formed value: nvidia.com/gpu

### ISSUE THREAD

**Issue by dmarcus-wire** [redhat-na-ssa/demo-ocp-gpu#4]
deploying to a 4.13 env., I get this warning when running the . scripts/bootstrap.sh && ocp_aws_cluster_autoscaling

Warning: GPU accelerator label contains a poorly formed value: nvidia.com/gpu, errors: a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'). This is not an error but may cause issues when using GPU resource limits with the Cluster Autoscaler. For more information on the proper use of these values, please see https://access.redhat.com/solutions/6055181

**Comment by codekow** [comment]
Assuming OCP version `4.13.13`

**Comment by codekow** [comment]
Addressed in commit https://github.com/redhat-na-ssa/demo-ocp-gpu/commit/bde6b1962cfe265ea07f03b55d7149e542ac580d.

Updated the accelerator label to match docs.
