### ISSUE TITLE
update tested versions with AWS with OpenShift Open Environment 4.13.13

### ISSUE THREAD

**Issue by dmarcus-wire** [redhat-na-ssa/demo-ocp-gpu#5]
tested on demo.redhat.com AWS with OpenShift Open Environment 4.13.13

**Comment by codekow** [comment]
@dmarcus-wire Want to open a PR for this?

**Comment by codekow** [comment]
Addressed with commit d74c8c16b6db9bf89bf1bec8c49d2bda24e53e92
