### ISSUE TITLE
warning with Dev Spaces during bootstrap

### ISSUE THREAD

**Issue by dmarcus-wire** [redhat-na-ssa/demo-ocp-gpu#6]
when running . scripts/bootstrap.sh && setup_operator_devspaces

I get this:  Warning: resource devworkspaceoperatorconfigs/devworkspace-config is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by oc apply. oc apply should only be used on resources created declaratively by either oc create --save-config or oc apply. The missing annotation will be patched automatically.

**Comment by codekow** [comment]
This has been addressed and now the operator for Dev Spaces checks for that CRD before moving forward.

Thanks for submitting this issue! :+1:
