### ISSUE TITLE
I have 2 console-{id} pods Pending on my single Controller cluster

### ISSUE THREAD

**Issue by dmarcus-wire** [redhat-na-ssa/demo-ocp-gpu#7]
in the 'openshift-console' project 

there are 2 pods that is hanging for the GPU metrics

"Generated from cluster-autoscaler
23 times in the last 5 minutes
pod didn't trigger scale-up: 2 node(s) didn't match Pod's node affinity/selector"

we edited the oc edit consoles.operator.openshift.io/cluster to remove the duplicate console-plugin-nvidia-gpu

Spec:
  Log Level:           Normal
  Management State:    Managed
  Operator Log Level:  Normal
  Plugins:
    console-plugin-nvidia-gpu
    console-plugin-nvidia-gpu

then did oc delete pod --all

**Comment by codekow** [comment]
Unfortunately this is a cluster specific issue.

Closing unless there are some docs to update specifically.
